repos:
  - repo: local
    hooks:
      - id: django-tests
        name: Run Django test suite before commit
        entry: bash
        language: system
        pass_filenames: false
        args:
          - -lc
          - |
            set -euo pipefail
            echo "[pre-commit] Running Django tests..."
            if command -v uv >/dev/null 2>&1; then
              uv run python manage.py test -v 2
            else
              python manage.py test -v 2
            fi
        stages: [pre-commit]