version: "3.9"

services:
  db:
    image: postgres:16-alpine
    # Uncomment if you want to enforce ARM64 (Oracle Ampere). On x86 dev machines, leave it commented.
    # platform: linux/arm64
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-ecom}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      # platform: linux/arm64
    env_file:
      - .env
    environment:
      # Provide a sane default for DATABASE_URL if not set in .env
      DATABASE_URL: ${DATABASE_URL:-postgresql://app:app@db:5432/ecom}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - staticfiles:/app/staticfiles
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  postgres-data:
  staticfiles: